// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pardingtekslklnvglzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcmRpbmd0ZWtzbGtsbnZnbHpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzIwNjIsImV4cCI6MjA3MzM0ODA2Mn0.IMwQe5awCE3RXBk8uiDEcSFWG_8oFpU52w42UDbW-Eo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});